[store.primary]
  connection = "postgresql://postgres:let-me-in@postgres/subgraph?sslmode=prefer"
  weight = 1
  pool_size = 10
  pruning = "window:100000"

[chains]
  ingestor = "index_node"
  [chains.mainnet]
    shard = "primary"
    [[chains.mainnet.provider]]
      label = "mainnet"
      url = "https://andromeda.metis.io/?owner=1088"
      features = ["archive","traces"]
      transport = "rpc"

[deployment]
[[deployment.rule]]
  shard = "primary"
  indexers = [ "index_node" ]